### ISSUE TITLE
CanAttack hook not working in Rust

### ISSUE THREAD

**Issue by KovalevPW** [OxideMod/Oxide#1070]
```
Protocol: 1979.143.1
Build Version: 1219.74
Build Date: Thursday, April 13, 2017 6:42:40 PM
Unity Version: 5.6.0f3
Changeset: 20190
Branch: /main
Oxide Version: 2.0.3195
```

```
namespace Oxide.Plugins
{
    [Info("TestPlugin", "TestPlugin", "1.0.0")]
    public class TestPlugin : RustPlugin {
        void CanAttack(BasePlayer player) {
            Puts("CanAttack works!");
        }
    }
}
```
http://oxidemod.org/threads/canattack-hook-not-working.24906/

**Comment by Mughisi** [comment]
The server no longer checks if a player is able to attack, this logic is now only executed on the client. Because of this the hook is no longer being called. For that reason the hook has been removed but it should be possible to recreate CanAttack in some extent by utilizing the various attack hooks (OnMeleeThrown, OnWeaponFired,...) 

For melee attacks the hook OnMeleeAttack(BasePlayer player attacker, HitInfo info) was added (returning a non-null value overrides default behavior)
