### ISSUE TITLE
Rust: Only admin users call DoImmediateDemolish, Normal users call DoDemolish

### ISSUE THREAD

**Issue by AEtherSurfer** [OxideMod/Oxide#628]
Current `OnStructureDemolish` hook is wired to `DoImmediateDemolish`.

`DoImmediateDemolish` is only invoked by admin players.

Please change it to hook into `DoDemolish` function instead as that seems to be the function invoked by regular non admin players.

Maybe add an `OnStructureDemolishAdmin` that hooks `DoImmediateDemolish`.  Maybe better to call it `OnStructureDemolishImmediate` to match with what an admin sees in the right click round circle menu?

An admin can actually see the normal player demolish alongside the admin 'immediate' demolish when they are authorized on the local cupboard.

References:
- http://docs.oxidemod.org/rust/#onstructuredemolish
- https://github.com/OxideMod/Oxide/commit/5c7ffe3fda668b36c508d4cdbe0f1cfc267be329#diff-192d9a78b0a735bc839b58dc38e85eaeR1132

**Comment by Mughisi** [comment]
At the time those hooks were added (nearly a year ago) the immediate demolish was the only one available, But as there is a separate demolish option for players then it should be added as well, but instead of using `OnStructureDemolishImmediate`or `OnStructureDemolishAdmin` I would probably stick to `OnStructureDemolish` and have it called by both `DoDemolish` and `DoImmediateDemolish` and pass an extra argument.
Something along the lines of `OnStructureDemolish(BuildingBlock block, BasePlayer player, bool isImmediate)`

**Comment by AEtherSurfer** [comment]
Re: is immediate flag

That works for me.
